global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'  # Specify the metrics path
    static_configs:
      - targets: ['backend:7000']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
    metrics_path: '/prometheus'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

