services:
  backend:
    image: ${BACKEND_IMAGE_NAME}:${BACKEND_DEPLOY_TAG}
    #image: sirdocker/ccsd-project-backend:4
    ports:
      - "7000:7000"
    volumes:
      - ~/web-app/db:/app/db
    networks:
      - web-app-network

  frontend:
    image: ${FRONTEND_IMAGE_NAME}:${FRONTEND_DEPLOY_TAG}
    #image: sirdocker/ccsd-project-frontend:4
    ports:
      - "9000:9000"
    networks:
      - web-app-network
    depends_on:
      - backend

networks:
  web-app-network:
    driver: bridge